stages:
- name: run
  steps:
  - runScriptConfig:
      image: centos:latest
      shellScript: sleep 60
  - runScriptConfig:
      image: centos:latest
      shellScript: sleep 50
timeout: 60
branch: {}
